"use client";

import { useState, useEffect, useCallback, useRef } from "react";
import Link from "next/link";

/* ── Types ── */
interface Idea {
  id: string;
  title: string;
  summary: string;
  status: "raw" | "expanded" | "queued" | "promoted" | "zombie" | "graveyard";
  tags: string[];
  excitement: number; // 1-5
  image_url: string | null;
  created_at: string;
}

/* ── Constants ── */
const TOKEN = "apex-live-2026";

const STATUS_STYLES: Record<string, { bg: string; text: string; label: string }> = {
  raw: { bg: "rgba(107,107,128,0.15)", text: "#6b6b80", label: "Raw" },
  expanded: { bg: "rgba(96,165,250,0.15)", text: "#60a5fa", label: "Expanded" },
  queued: { bg: "rgba(0,212,212,0.15)", text: "#00d4d4", label: "Queued" },
  promoted: { bg: "rgba(34,197,94,0.15)", text: "#22c55e", label: "Promoted" },
  zombie: { bg: "rgba(245,158,11,0.15)", text: "#f59e0b", label: "Zombie" },
  graveyard: { bg: "rgba(55,55,70,0.3)", text: "#4a4a5a", label: "Graveyard" },
};

const PLACEHOLDER_TEXTS = [
  "What problem did you notice today?",
  "What would you build with unlimited engineers?",
  "What's broken about healthcare?",
  "I wish there was a tool that...",
  "What would you build with unlimited engineers?",
  "What's broken about real estate?",
  "What would you automate if you could?",
];

const SORT_OPTIONS = [
  { value: "newest", label: "Newest" },
  { value: "oldest", label: "Oldest" },
  { value: "status", label: "Status" },
  { value: "promoted-first", label: "Promoted First" },
];

const STATUS_FILTERS = ["all", "raw", "expanded", "queued", "promoted", "zombie", "graveyard"];

const GRADIENT_PALETTES = [
  "linear-gradient(135deg, #0d1b2a 0%, #1b2838 50%, #0a1628 100%)",
  "linear-gradient(135deg, #1a0a2e 0%, #16213e 50%, #0f3460 100%)",
  "linear-gradient(135deg, #0b1d0b 0%, #1a2e1a 50%, #0d2818 100%)",
  "linear-gradient(135deg, #2d1b00 0%, #1a1a2e 50%, #0a0a1f 100%)",
  "linear-gradient(135deg, #1a0000 0%, #2d1a1a 50%, #1a0a1a 100%)",
  "linear-gradient(135deg, #001a1a 0%, #0a2828 50%, #001414 100%)",
];

/* ── Seed Data ── */
const SEED_IDEAS: Idea[] = [
  {
    id: "idea-repostai",
    title: "RepostAI",
    summary: "AI-powered content repurposing engine — one post becomes 10 across all platforms with optimised formats.",
    status: "expanded",
    tags: ["AI", "Content", "SaaS"],
    excitement: 5,
    image_url: null,
    created_at: "2026-03-25T10:00:00Z",
  },
  {
    id: "idea-parliament",
    title: "Parliament Tracker",
    summary: "Track MP voting patterns, detect contradictions, and surface hidden voting trends with AI analysis.",
    status: "promoted",
    tags: ["GovTech", "Data", "AI"],
    excitement: 4,
    image_url: null,
    created_at: "2026-03-20T14:00:00Z",
  },
  {
    id: "idea-comic",
    title: "Comic Creator",
    summary: "Turn any story prompt into a full comic book with AI-generated panels, speech bubbles, and consistent characters.",
    status: "raw",
    tags: ["Creative", "AI", "Consumer"],
    excitement: 4,
    image_url: null,
    created_at: "2026-03-28T09:00:00Z",
  },
  {
    id: "idea-peptide-stack",
    title: "Peptide Stack Builder",
    summary: "Interactive tool that recommends peptide stacks based on goals, body stats, and experience level.",
    status: "queued",
    tags: ["Health", "Tool", "Caliber"],
    excitement: 3,
    image_url: null,
    created_at: "2026-03-22T16:00:00Z",
  },
  {
    id: "idea-villa-investor",
    title: "Villa Investor Platform",
    summary: "Marketplace connecting villa investors with property managers — fractional ownership, yield tracking, automated reporting.",
    status: "raw",
    tags: ["PropTech", "Marketplace", "Finance"],
    excitement: 3,
    image_url: null,
    created_at: "2026-03-27T11:00:00Z",
  },
  {
    id: "idea-market-intel",
    title: "Market Intel as a Service",
    summary: "On-demand market research reports generated by AI agents — competitor analysis, pricing intel, trend forecasting.",
    status: "zombie",
    tags: ["B2B", "AI", "Research"],
    excitement: 2,
    image_url: null,
    created_at: "2026-03-15T08:00:00Z",
  },
];

const MOCK_SIGNALS = [
  { title: "AI wrappers are dead, AI agents are the new play", source: "@levelsio", time: "2h ago" },
  { title: "Voice-first interfaces converting 3x better than chat", source: "@sama", time: "5h ago" },
  { title: "Solo founders hitting $10k MRR in 30 days with Claude", source: "@marc_lou", time: "8h ago" },
  { title: "The peptide market is exploding — $45B by 2028", source: "@healthtech_vc", time: "1d ago" },
];

const MOCK_VIDEOS = [
  { title: "How I Built a $1M SaaS in 90 Days", channel: "Starter Story", views: "342K" },
  { title: "The Future of AI Agents in Business", channel: "Y Combinator", views: "1.2M" },
  { title: "Building in Public: Week 12 Update", channel: "Pieter Levels", views: "89K" },
  { title: "Why Micro-SaaS is the Best Business Model", channel: "MicroConf", views: "156K" },
];

const MOCK_TRENDS = [
  { title: "AI-powered compliance tools seeing 400% growth", category: "RegTech" },
  { title: "Voice cloning costs dropped 90% in 6 months", category: "AI Audio" },
  { title: "Vertical SaaS for trades — plumbing, HVAC, electrical", category: "B2B" },
  { title: "Peptide research APIs becoming mainstream", category: "BioTech" },
];

const CAPABILITIES = [
  "Claude can build full apps from a single prompt",
  "Voice cloning is now real-time at $0.001/sec",
  "GPT-image-1 generates indistinguishable product photography",
  "Browser-use agents can navigate any website autonomously",
];

/* ── Component ── */
export default function IdeasPage() {
  const [ideas, setIdeas] = useState<Idea[]>(SEED_IDEAS);
  const [inputValue, setInputValue] = useState("");
  const [placeholderIdx, setPlaceholderIdx] = useState(0);
  const [statusFilter, setStatusFilter] = useState("all");
  const [tagFilter, setTagFilter] = useState("");
  const [searchText, setSearchText] = useState("");
  const [sortBy, setSortBy] = useState("newest");
  const [submitting, setSubmitting] = useState(false);
  const [collapsedPanels, setCollapsedPanels] = useState<Set<string>>(new Set());
  const inputRef = useRef<HTMLTextAreaElement>(null);

  // Rotate placeholder
  useEffect(() => {
    const timer = setInterval(() => {
      setPlaceholderIdx((i) => (i + 1) % PLACEHOLDER_TEXTS.length);
    }, 3000);
    return () => clearInterval(timer);
  }, []);

  // Fetch ideas
  const fetchIdeas = useCallback(async () => {
    try {
      const res = await fetch("/api/map-room/ideas");
      if (res.ok) {
        const data = await res.json();
        const items = data?.items || data?.ideas;
        if (items?.length) {
          // Map API shape (name, etc.) to our Idea shape
          const statusMap: Record<string, string> = {
            exploring: "expanded",
            validated: "queued",
            parked: "zombie",
            killed: "graveyard",
          };
          setIdeas(items.map((i: Record<string, unknown>) => ({
            id: i.id,
            title: i.name || i.title || "Untitled",
            summary: i.summary || "",
            status: statusMap[i.status as string] || i.status || "raw",
            tags: i.tags || [],
            excitement: i.excitement || 3,
            image_url: i.image_url || null,
            created_at: i.created_at || new Date().toISOString(),
          })));
        }
      }
    } catch {
      // keep seed data
    }
  }, []);

  useEffect(() => {
    fetchIdeas();
  }, [fetchIdeas]);

  // Submit idea
  const handleSubmit = async () => {
    if (!inputValue.trim()) return;
    setSubmitting(true);
    try {
      const res = await fetch("/api/map-room/ideas", {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${TOKEN}` },
        body: JSON.stringify({ title: inputValue.trim(), summary: "", status: "raw", tags: [], excitement: 1 }),
      });
      if (res.ok) {
        setInputValue("");
        fetchIdeas();
      }
    } catch {
      // Optimistic local add
      const newIdea: Idea = {
        id: `idea-${Date.now()}`,
        title: inputValue.trim(),
        summary: "",
        status: "raw",
        tags: [],
        excitement: 1,
        image_url: null,
        created_at: new Date().toISOString(),
      };
      setIdeas((prev) => [newIdea, ...prev]);
      setInputValue("");
    }
    setSubmitting(false);
  };

  const togglePanel = (name: string) => {
    setCollapsedPanels((prev) => {
      const next = new Set(prev);
      next.has(name) ? next.delete(name) : next.add(name);
      return next;
    });
  };

  // Collect all tags
  const allTags = Array.from(new Set(ideas.flatMap((i) => i.tags))).sort();

  // Filter & sort
  let filtered = ideas.filter((idea) => {
    if (statusFilter !== "all" && idea.status !== statusFilter) return false;
    if (tagFilter && !idea.tags.includes(tagFilter)) return false;
    if (searchText) {
      const q = searchText.toLowerCase();
      if (!idea.title.toLowerCase().includes(q) && !idea.summary.toLowerCase().includes(q)) return false;
    }
    return true;
  });

  filtered = [...filtered].sort((a, b) => {
    switch (sortBy) {
      case "oldest":
        return new Date(a.created_at).getTime() - new Date(b.created_at).getTime();
      case "status": {
        const order = ["promoted", "queued", "expanded", "raw", "zombie", "graveyard"];
        return order.indexOf(a.status) - order.indexOf(b.status);
      }
      case "promoted-first": {
        if (a.status === "promoted" && b.status !== "promoted") return -1;
        if (b.status === "promoted" && a.status !== "promoted") return 1;
        return new Date(b.created_at).getTime() - new Date(a.created_at).getTime();
      }
      default:
        return new Date(b.created_at).getTime() - new Date(a.created_at).getTime();
    }
  });

  return (
    <div className="space-y-6 animate-in fade-in duration-500">
      {/* ── Quick Capture Bar ── */}
      <section className="rounded-xl border p-6" style={{ background: "#111118", borderColor: "#1e1e2e" }}>
        <div className="flex items-center gap-2 mb-3">
          <span className="text-lg">💡</span>
          <h2 className="text-sm font-semibold uppercase tracking-wider" style={{ color: "#6b6b80" }}>
            Quick Capture
          </h2>
        </div>
        <div className="flex gap-3">
          <div className="flex-1 relative">
            <textarea
              ref={inputRef}
              value={inputValue}
              onChange={(e) => setInputValue(e.target.value)}
              placeholder={PLACEHOLDER_TEXTS[placeholderIdx]}
              onKeyDown={(e) => {
                if (e.key === "Enter" && !e.shiftKey) {
                  e.preventDefault();
                  handleSubmit();
                }
              }}
              rows={2}
              className="w-full rounded-lg border px-4 py-3 text-sm resize-none focus:outline-none transition-colors placeholder-[#4a4a5a]"
              style={{
                background: "#0a0a0f",
                borderColor: "#1e1e2e",
                color: "#ffffff",
                fontFamily: "'Inter', sans-serif",
              }}
            />
          </div>
          <div className="flex flex-col gap-2">
            <button
              onClick={handleSubmit}
              disabled={submitting || !inputValue.trim()}
              className="px-5 py-3 rounded-lg text-sm font-semibold transition-all disabled:opacity-30 cursor-pointer"
              style={{
                background: "rgba(0,212,212,0.15)",
                color: "#00d4d4",
                border: "1px solid rgba(0,212,212,0.3)",
              }}
            >
              {submitting ? "..." : "Capture"}
            </button>
            <button
              className="px-3 py-2 rounded-lg text-xs transition-all cursor-pointer flex items-center justify-center gap-1"
              style={{
                background: "rgba(107,107,128,0.1)",
                color: "#6b6b80",
                border: "1px solid rgba(107,107,128,0.2)",
              }}
              title="Voice capture (placeholder)"
            >
              🎤
              <span
                className="text-[8px] px-1 py-0.5 rounded"
                style={{ background: "rgba(107,107,128,0.15)", color: "#6b6b80" }}
              >
                🔌
              </span>
            </button>
          </div>
        </div>
      </section>

      {/* ── Filters & Sort ── */}
      <section className="flex flex-wrap items-center gap-3">
        {/* Status pills */}
        <div className="flex items-center gap-1 flex-wrap">
          {STATUS_FILTERS.map((s) => {
            const isActive = statusFilter === s;
            const style = s === "all" ? null : STATUS_STYLES[s];
            return (
              <button
                key={s}
                onClick={() => setStatusFilter(s)}
                className="px-3 py-1.5 rounded-full text-xs font-medium transition-all cursor-pointer"
                style={{
                  background: isActive
                    ? style?.bg || "rgba(0,212,212,0.15)"
                    : "rgba(30,30,46,0.5)",
                  color: isActive
                    ? style?.text || "#00d4d4"
                    : "#6b6b80",
                  border: `1px solid ${isActive ? (style?.text || "#00d4d4") + "33" : "#1e1e2e"}`,
                }}
              >
                {s === "all" ? "All" : STATUS_STYLES[s]?.label || s}
              </button>
            );
          })}
        </div>

        {/* Tag filter */}
        <select
          value={tagFilter}
          onChange={(e) => setTagFilter(e.target.value)}
          className="px-3 py-1.5 rounded-lg text-xs cursor-pointer focus:outline-none"
          style={{ background: "#111118", border: "1px solid #1e1e2e", color: "#a0a0b0" }}
        >
          <option value="">All Tags</option>
          {allTags.map((t) => (
            <option key={t} value={t}>{t}</option>
          ))}
        </select>

        {/* Search */}
        <input
          type="text"
          value={searchText}
          onChange={(e) => setSearchText(e.target.value)}
          placeholder="Search ideas..."
          className="px-3 py-1.5 rounded-lg text-xs focus:outline-none flex-1 min-w-[120px] max-w-[250px]"
          style={{ background: "#111118", border: "1px solid #1e1e2e", color: "#a0a0b0" }}
        />

        {/* Sort */}
        <select
          value={sortBy}
          onChange={(e) => setSortBy(e.target.value)}
          className="px-3 py-1.5 rounded-lg text-xs cursor-pointer focus:outline-none ml-auto"
          style={{ background: "#111118", border: "1px solid #1e1e2e", color: "#a0a0b0" }}
        >
          {SORT_OPTIONS.map((o) => (
            <option key={o.value} value={o.value}>{o.label}</option>
          ))}
        </select>
      </section>

      {/* ── Main Layout: Grid + Sidebar ── */}
      <div className="flex gap-6 flex-col lg:flex-row">
        {/* ── Idea Grid ── */}
        <div className="flex-1 min-w-0">
          {filtered.length === 0 && (
            <div className="rounded-xl border p-12 text-center" style={{ background: "#111118", borderColor: "#1e1e2e" }}>
              <div className="text-3xl mb-3">🌱</div>
              <p className="text-sm" style={{ color: "#a0a0b0" }}>No ideas match your filters.</p>
              <p className="text-xs mt-1" style={{ color: "#6b6b80" }}>Try adjusting your filters or capture a new idea above.</p>
            </div>
          )}

          <div className="columns-1 md:columns-2 xl:columns-3 gap-4 space-y-4">
            {filtered.map((idea, idx) => {
              const statusStyle = STATUS_STYLES[idea.status];
              const gradient = GRADIENT_PALETTES[idx % GRADIENT_PALETTES.length];
              return (
                <Link
                  key={idea.id}
                  href={`/map-room/ideas/${idea.id}`}
                  className="block rounded-xl border overflow-hidden break-inside-avoid transition-all hover:border-[#2a2a3e] hover:translate-y-[-2px] group"
                  style={{ background: "#111118", borderColor: "#1e1e2e" }}
                >
                  {/* Image / Gradient placeholder */}
                  {idea.image_url ? (
                    <div
                      className="w-full aspect-video bg-cover bg-center"
                      style={{ backgroundImage: `url(${idea.image_url})` }}
                    />
                  ) : (
                    <div
                      className="w-full aspect-video flex items-center justify-center"
                      style={{ background: gradient }}
                    >
                      <span className="text-3xl opacity-30 group-hover:opacity-50 transition-opacity">
                        💡
                      </span>
                    </div>
                  )}

                  <div className="p-4">
                    {/* Title */}
                    <h3 className="text-sm font-bold text-white mb-1 group-hover:text-[#00d4d4] transition-colors">
                      {idea.title}
                    </h3>

                    {/* Summary */}
                    {idea.summary && (
                      <p className="text-xs leading-relaxed mb-3" style={{ color: "#a0a0b0" }}>
                        {idea.summary.length > 100 ? idea.summary.slice(0, 100) + "..." : idea.summary}
                      </p>
                    )}

                    {/* Bottom row */}
                    <div className="flex items-center justify-between">
                      {/* Status badge */}
                      <span
                        className="text-[10px] font-semibold px-2 py-0.5 rounded-full uppercase tracking-wider"
                        style={{ background: statusStyle.bg, color: statusStyle.text }}
                      >
                        {statusStyle.label}
                      </span>

                      {/* Excitement */}
                      <div className="flex items-center gap-0.5">
                        {Array.from({ length: 5 }).map((_, i) => (
                          <span
                            key={i}
                            className="text-[10px]"
                            style={{ opacity: i < idea.excitement ? 1 : 0.2 }}
                          >
                            ⚡
                          </span>
                        ))}
                      </div>
                    </div>

                    {/* Tags */}
                    {idea.tags.length > 0 && (
                      <div className="flex flex-wrap gap-1 mt-2">
                        {idea.tags.map((tag) => (
                          <span
                            key={tag}
                            className="text-[9px] px-1.5 py-0.5 rounded-full"
                            style={{ background: "rgba(0,212,212,0.08)", color: "#00d4d4" }}
                          >
                            {tag}
                          </span>
                        ))}
                      </div>
                    )}
                  </div>
                </Link>
              );
            })}
          </div>
        </div>

        {/* ── Right Sidebar: Inspiration Panels ── */}
        <div className="w-full lg:w-80 flex-shrink-0 space-y-4">
          {/* Twitter/X Signals */}
          <InspirationPanel
            title="Twitter/X Signals"
            icon="🐦"
            placeholder
            collapsed={collapsedPanels.has("twitter")}
            onToggle={() => togglePanel("twitter")}
          >
            {MOCK_SIGNALS.map((s, i) => (
              <div key={i} className="px-3 py-2.5 border-b last:border-b-0" style={{ borderColor: "#1e1e2e" }}>
                <p className="text-xs text-white leading-relaxed">{s.title}</p>
                <div className="flex items-center gap-2 mt-1 text-[10px]" style={{ color: "#6b6b80" }}>
                  <span>{s.source}</span>
                  <span>·</span>
                  <span>{s.time}</span>
                </div>
              </div>
            ))}
          </InspirationPanel>

          {/* YouTube Watchlist */}
          <InspirationPanel
            title="YouTube Watchlist"
            icon="📺"
            placeholder
            collapsed={collapsedPanels.has("youtube")}
            onToggle={() => togglePanel("youtube")}
          >
            {MOCK_VIDEOS.map((v, i) => (
              <div key={i} className="px-3 py-2.5 border-b last:border-b-0" style={{ borderColor: "#1e1e2e" }}>
                <p className="text-xs text-white leading-relaxed">{v.title}</p>
                <div className="flex items-center gap-2 mt-1 text-[10px]" style={{ color: "#6b6b80" }}>
                  <span>{v.channel}</span>
                  <span>·</span>
                  <span>{v.views} views</span>
                </div>
              </div>
            ))}
          </InspirationPanel>

          {/* News/Trends */}
          <InspirationPanel
            title="News & Trends"
            icon="📈"
            placeholder
            collapsed={collapsedPanels.has("trends")}
            onToggle={() => togglePanel("trends")}
          >
            {MOCK_TRENDS.map((t, i) => (
              <div key={i} className="px-3 py-2.5 border-b last:border-b-0" style={{ borderColor: "#1e1e2e" }}>
                <p className="text-xs text-white leading-relaxed">{t.title}</p>
                <span
                  className="inline-block text-[9px] px-1.5 py-0.5 rounded-full mt-1"
                  style={{ background: "rgba(96,165,250,0.12)", color: "#60a5fa" }}
                >
                  {t.category}
                </span>
              </div>
            ))}
          </InspirationPanel>

          {/* Capabilities Feed */}
          <InspirationPanel
            title="Capabilities Feed"
            icon="🧠"
            collapsed={collapsedPanels.has("capabilities")}
            onToggle={() => togglePanel("capabilities")}
          >
            {CAPABILITIES.map((c, i) => (
              <div key={i} className="px-3 py-2.5 border-b last:border-b-0" style={{ borderColor: "#1e1e2e" }}>
                <p className="text-xs leading-relaxed" style={{ color: "#a0a0b0" }}>{c}</p>
              </div>
            ))}
          </InspirationPanel>
        </div>
      </div>

      <style jsx>{`
        @keyframes fadeIn {
          from { opacity: 0; transform: translateY(8px); }
          to { opacity: 1; transform: translateY(0); }
        }
        .animate-in {
          animation: fadeIn 0.5s ease-out;
        }
      `}</style>
    </div>
  );
}

/* ── Inspiration Panel ── */
function InspirationPanel({
  title,
  icon,
  placeholder,
  collapsed,
  onToggle,
  children,
}: {
  title: string;
  icon: string;
  placeholder?: boolean;
  collapsed: boolean;
  onToggle: () => void;
  children: React.ReactNode;
}) {
  return (
    <div className="rounded-xl border overflow-hidden" style={{ background: "#111118", borderColor: "#1e1e2e" }}>
      <button
        onClick={onToggle}
        className="w-full px-4 py-3 flex items-center justify-between cursor-pointer hover:bg-white/[0.02] transition-colors"
      >
        <div className="flex items-center gap-2">
          <span className="text-sm">{icon}</span>
          <span className="text-xs font-semibold uppercase tracking-wider" style={{ color: "#a0a0b0" }}>
            {title}
          </span>
          {placeholder && (
            <span
              className="text-[8px] px-1.5 py-0.5 rounded"
              style={{ background: "rgba(107,107,128,0.15)", color: "#6b6b80" }}
            >
              🔌 PLACEHOLDER
            </span>
          )}
        </div>
        <svg
          className="w-3 h-3 transition-transform"
          style={{ transform: collapsed ? "rotate(0deg)" : "rotate(180deg)", color: "#6b6b80" }}
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
          strokeWidth={2}
        >
          <path strokeLinecap="round" strokeLinejoin="round" d="M19 9l-7 7-7-7" />
        </svg>
      </button>
      {!collapsed && <div>{children}</div>}
    </div>
  );
}
